### ISSUE TITLE
Kallisto Bus doesn't give output

### ISSUE THREAD

**Issue by rbarbieri86** [Mayrlab/scUTRquant#92]
Hello,

I am trying to have scUTRquant analyze a small scRNA-seq dataset (3 controls, 3 alternate). 
I have written the **config.yaml** and the **sample.csv** and placed them in a different folder than the scUTRquant one.
The files should be correctly pointed at with a full path, however I get this error:

```bash
snakemake --use-conda --cores 8 --configfile ~/athero_scRNA/config.yaml
Config file config.yaml is extended by additional config specified via the command line.
[INFO] scUTRquant v0.5.0
[INFO] Loading sample data...
[INFO] Loaded 2 samples.
Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
MissingInputException in rule mtxs_to_sce_genes in file /q/home/barbieri/scUTRquant/Snakefile, line 315:
Missing input files for rule mtxs_to_sce_genes:
    output: data/sce/utrome_mm10_v2/Athero_Clement.genes.Rds
    wildcards: target=utrome_mm10_v2
    affected files:
        data/kallisto/utrome_mm10_v2/A9/genes.barcodes.txt
        data/kallisto/utrome_mm10_v2/A10/genes.mtx
        data/kallisto/utrome_mm10_v2/A9/genes.mtx
        data/kallisto/utrome_mm10_v2/A10/genes.barcodes.txt
        data/kallisto/utrome_mm10_v2/A10/genes.genes.txt
        data/kallisto/utrome_mm10_v2/A9/genes.genes.txt
```

So it looks like `kallisto bus` is not providing the expected output. For reference here is the content of the **config.yaml** I am using:

```yaml
dataset_name: "Athero_Clement"
sample_file: "/q/home/barbieri/athero_scRNA/Athero_Clement.csv"
sample_regex: ".fastq"
tech: "10xv2"
strand: "--fr-stranded"
cell_annots: null
cell_annots_key: "cell_id"
exclude_unannotated_cells: False
target: "utrome_mm10_v2"
output_type:
  - "genes"
  - "txs"
output_format:
  - "sce"
tmp_dir: "/q/home/barbieri/athero_scRNA/tmp"
bx_whitelist: "/q/home/barbieri/scUTRquant/extdata/bxs/737K-august-2016.txt"
correct_bus: True
min_umis: 500
targets_config: "/q/home/barbieri/scUTRquant/extdata/targets/targets.yaml"
use_hdf5: False
include_reports: True
```

Many thanks in advance for any pointers :)
